import { Link } from 'react-router-dom'
import { useState } from 'react'
import { getCart, getSavedLocation } from '../data/marketplace'
import { addBuyerRequest } from '../data/sellerData'

export function Checkout() {
  const cart = getCart(); const saved = getSavedLocation(); const [address, setAddress] = useState({ name: '', phone: '', address: '', district: saved.district, pin: saved.pin }); const [payment, setPayment] = useState('UPI'); const [notice, setNotice] = useState('')
  const productTotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); const delivery = productTotal ? 49 : 0; const total = productTotal + delivery
  const placeOrder = (event) => { event.preventDefault(); const profile = (() => { try { return JSON.parse(localStorage.getItem('drPlantProfile') || 'null') } catch { return null } })(); cart.forEach((item) => addBuyerRequest({ id: `request-${Date.now()}-${item.id}`, buyerName: address.name || profile?.name || 'Buyer', product: item.name, quantity: item.quantity, unit: 'items', district: address.district, city: saved.city, pin: address.pin, date: new Date().toLocaleDateString('en-IN'), amount: item.price * item.quantity, status: 'Pending', shopDistrict: address.district })); setNotice('Buyer request sent. Payment is not processed in this frontend demo; the shop owner can accept or reject your request.'); }
  if (!cart.length) return <div className="container page-shell empty-state"><h1>Your cart is empty</h1><Link to="/shop" className="primary-btn">Return to Shop</Link></div>
  return <div className="container page-shell checkout-page"><div className="page-intro"><span className="eyebrow">Buyer request</span><h1>Checkout</h1><p>Send your request to the local shop. Payment is not processed until a real backend gateway is connected.</p></div><form className="checkout-layout" onSubmit={placeOrder}><div className="checkout-main"><section className="checkout-section"><h2>Delivery address</h2><div className="form-grid"><label>Name<input required value={address.name} onChange={(e) => setAddress({ ...address, name: e.target.value })} placeholder="Your name" /></label><label>Phone<input required value={address.phone} onChange={(e) => setAddress({ ...address, phone: e.target.value })} placeholder="10-digit mobile number" /></label><label className="span-2">Address<input required value={address.address} onChange={(e) => setAddress({ ...address, address: e.target.value })} placeholder="House, road, village or town" /></label><label>District<input required value={address.district} onChange={(e) => setAddress({ ...address, district: e.target.value })} /></label><label>PIN Code<input required value={address.pin} onChange={(e) => setAddress({ ...address, pin: e.target.value })} inputMode="numeric" placeholder="411001" /></label></div></section><section className="checkout-section"><h2>Choose Payment Method</h2><div className="payment-options">{['UPI', 'Cash on Delivery', 'Online Payment'].map((method) => <label key={method} className={payment === method ? 'payment-option active' : 'payment-option'}><input type="radio" name="payment" value={method} checked={payment === method} onChange={(e) => setPayment(e.target.value)} /><span><strong>{method}</strong><small>{method === 'Cash on Delivery' ? 'Availability depends on seller and area' : 'Ready for future gateway integration'}</small></span></label>)}</div>{notice && <p className="payment-notice">{notice}</p>}</section></div><aside className="order-summary"><span className="eyebrow">Review</span><h2>Request summary</h2>{cart.map((item) => <div className="summary-line" key={item.id}><span>{item.name} × {item.quantity}</span><strong>₹{item.price * item.quantity}</strong></div>)}<div className="summary-line"><span>Product total</span><strong>₹{productTotal}</strong></div><div className="summary-line"><span>Delivery fee</span><strong>₹{delivery}</strong></div><div className="summary-total"><span>Total</span><strong>₹{total}</strong></div><button className="primary-btn full-btn" type="submit">Send Buyer Request</button></aside></form></div>
}
