import { Check, MessageCircle, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getSellerProfile, getSellerRequests, getSellerOrders, saveSellerOrders, saveSellerRequests } from '../data/sellerData'

export function SellerRequests() {
  const [requests, setRequests] = useState(getSellerRequests()); const profile = getSellerProfile()
  const update = (id, status) => { const next = requests.map((request) => request.id === id ? { ...request, status } : request); setRequests(next); saveSellerRequests(next); saveSellerOrders(getSellerOrders().map((order) => order.id === id ? { ...order, status: status === 'Confirmed' ? 'Accepted' : status } : order)) }
  useEffect(() => { const sync = () => setRequests(getSellerRequests()); window.addEventListener('drPlantRequestsUpdated', sync); return () => window.removeEventListener('drPlantRequestsUpdated', sync) }, [])
  return <div className="seller-container"><div className="seller-page-heading"><div><span className="eyebrow">{profile.location.district} matching</span><h1>Buyer Requests</h1><p>Requests from your district are listed first. Backend matching can replace this mock data later.</p></div></div><section className="seller-panel"><div className="seller-table-wrap"><table className="seller-table"><thead><tr><th>Buyer</th><th>Product</th><th>Location</th><th>Request date</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td><strong>{request.buyerName}</strong></td><td>{request.product}<small>{request.quantity} {request.unit}</small></td><td>{request.city}, {request.district}<small>PIN {request.pin}</small></td><td>{request.date}</td><td>₹{request.amount}</td><td><span className={`status-badge ${request.status.toLowerCase()}`}>{request.status}</span></td><td><div className="seller-row-actions">{request.status === 'Pending' && <><button className="table-action accept" onClick={() => update(request.id, 'Confirmed')}><Check size={14} /> Accept</button><button className="table-action reject" onClick={() => update(request.id, 'Rejected')}><X size={14} /> Reject</button></>}<a className="table-action" href="mailto:buyer@example.com"><MessageCircle size={14} /> Contact</a></div></td></tr>)}</tbody></table></div></section></div>
}
